name: scseq_env
channels:
  - pyg
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - conda-forge
  - bioconda
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.13
  - aiosignal=1.4.0
  - anyio=4.11.0
  - aom=3.6.1
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.1
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.22.0
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.4
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.1
  - azure-identity-cpp=1.13.2
  - azure-storage-blobs-cpp=12.15.0
  - azure-storage-common-cpp=12.11.0
  - azure-storage-files-datalake-cpp=12.13.0
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.2
  - cpuonly=2.0
  - cpython=3.10.19
  - cudatoolkit=11.6.2
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - dill=0.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=4.4.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.36.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarrow=22.0.0
  - libarrow-acero=22.0.0
  - libarrow-compute=22.0.0
  - libarrow-dataset=22.0.0
  - libarrow-substrait=22.0.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.86.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=22.0.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.08.12
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.20.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.11.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.6
  - networkx=3.4.2
  - ninja=1.13.0
  - nlohmann_json=3.12.0
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.3
  - openssl=3.5.4
  - orc=2.2.1
  - p11-kit=0.24.1
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pixman=0.46.4
  - platformdirs=4.3.8
  - prometheus-cpp=1.3.0
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow-core=22.0.0
  - pycparser=2.22
  - pyg=2.6.1
  - pygments=2.19.2
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python-gil=3.10.19
  - python-tzdata=2025.2
  - python-xxhash=3.6.0
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyzmq=27.0.0
  - re2=2025.08.12
  - readline=8.2
  - s2n=1.5.26
  - scikit-learn=1.7.0
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.57.1
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - urllib3=2.5.0
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxrender=0.9.12
  - xxhash=0.8.3
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - adjusttext==1.3.0
      - aicelltype==0.0.6
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - beautifulsoup4==4.13.4
      - biopython==1.85
      - blinker==1.9.0
      - boltons==25.0.0
      - celltypist==1.7.1
      - click==8.2.1
      - cmake==4.1.2
      - contourpy==1.3.2
      - ctxcore==0.2.0
      - cycler==0.12.1
      - cytoolz==1.0.1
      - dashscope==1.17.1
      - datetime==5.5
      - deprecated==1.2.18
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - filelock==3.13.1
      - flask==3.1.1
      - fonttools==4.58.5
      - formulaic==1.1.1
      - formulaic-contrasts==1.0.0
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - future==1.0.0
      - gdown==5.2.0
      - graphtools==1.5.3
      - grpcio==1.73.1
      - h5py==3.14.0
      - harmonypy==0.0.10
      - hf-xet==1.1.5
      - igraph==0.11.9
      - interface-meta==1.3.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - ktplotspy==0.3.2
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lifelines==0.30.0
      - lit==18.1.8
      - llvmlite==0.44.0
      - markdown==3.8.2
      - matplotlib==3.10.3
      - metatime==1.3.0
      - mizani==0.13.5
      - mofax==0.3.7
      - multiprocess==0.70.18
      - narwhals==1.46.0
      - natsort==8.4.0
      - nltk==3.9.2
      - numba==0.61.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.127
      - omicverse==1.7.1
      - openpyxl==3.1.5
      - pandas==2.3.1
      - patsy==1.0.1
      - pip==25.3
      - plotly==6.2.0
      - plotnine==0.14.6
      - progressbar2==4.5.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pycirclize==1.9.1
      - pydeseq2==0.5.2
      - pygam==0.9.1
      - pygsp==0.5.1
      - pymupdf==1.26.3
      - pymysql==1.1.1
      - pynndescent==0.5.13
      - pynvml==12.0.0
      - pyscience==0.5.0
      - python-dotplot==0.0.1
      - python-utils==3.9.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.31.0
      - safetensors==0.5.3
      - scanpy==1.11.3
      - scikit-misc==0.5.1
      - scipy==1.11.4
      - seaborn==0.13.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.2.1
      - session-info==1.0.1
      - session-info2==0.1.2
      - soupsieve==2.7
      - statsmodels==0.14.5
      - stdlib-list==0.11.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tasklogger==1.2.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - texttable==1.7.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - toolz==1.0.0
      - torch==2.5.1+cpu
      - torchaudio==2.6.0+cpu
      - torchvision==0.20.1
      - triton==3.2.0
      - umap-learn==0.5.9.post2
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - zope-interface==7.2
prefix: /public-SSD/home/sunpc/anaconda3/envs/aicelltype_env
